function show_zoom_window(fig)
  state = get(fig, 'UserData');
  if isempty(state.Extracted), errordlg('Load data first.'); return; end

  fi  = state.current_file_idx;
  chi = state.current_ch_idx;
  ext = state.Extracted(fi);
  time = ext.time;
  sig  = ext.data(:, chi);
  c = getappdata(fig, 'colors');

  win = figure('Name', sprintf('Electrode %s', ext.id_label{chi}), ...
                 'Position', [200 150 1500 560], ...
                 'Color', [0.15 0.15 0.18], ...
                 'NumberTitle', 'off', 'MenuBar', 'none');

  ax = axes('Parent', win, ...
    'Position',    [0.10 0.15 0.85 0.75], ...
    'Color',       [0.10 0.10 0.13], ...
    'XColor',      [0.7 0.7 0.7], ...
    'YColor',      [0.7 0.7 0.7], ...
    'XGrid',       'on', ...
    'YGrid',       'on', ...
    'GridColor',   [0.3 0.3 0.3], ...
    'FontSize',    11, ...
    'TickDir',     'out');

  plot(ax, time, sig, 'Color', c.accent, 'LineWidth', 1);

  set(ax, 'Color',    [0.10 0.10 0.13], ...
        'XColor',   [0.7 0.7 0.7], ...
        'YColor',   [0.7 0.7 0.7], ...
        'FontSize', 11, ...
        'XGrid',    'on', ...
        'YGrid',    'on');
  set(gca, "position", [0.1 0.1 0.8 0.8]);
  set(win, 'Color', [0.15 0.15 0.18]);
  drawnow();

  ylim(ax, state.y_limits);
  xlim(ax, [time(1) time(end)]);
  xlabel(ax, 'Time (s)', 'Color', [0.85 0.85 0.85], 'FontSize', 15);
  ylabel(ax, 'Signal (uV)', 'Color', [0.85 0.85 0.85], 'FontSize', 15);

  if state.spikes_computed
    hold(ax, 'on');
    thr = state.spike_thresh(chi);
    line(ax, [time(1) time(end)], [thr thr], ...
         'Color', 'r', 'LineStyle', '--', 'LineWidth', 1.2);
    st = state.spikes{chi};
    if ~isempty(st)
        yl         = ylim(ax);
        tick_height = (yl(2) - yl(1)) * 0.08;
        y_top      = yl(2) * 0.92;
        plot(ax, [st st]', ...
             [ones(size(st))*y_top, ones(size(st))*(y_top-tick_height)]', ...
             'r-', 'LineWidth', 1, 'HitTest', 'off');
    end
    hold(ax, 'off');
end

  zoom xon;
end

